version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: true
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
exclude_patterns:
  - "CoyoteUI/**/*"
