/*
 * Copyright (c) 2014 Stephan D. Cote' - All rights reserved.
 * 
 * This program and the accompanying materials are made available under the 
 * terms of the MIT License which accompanies this distribution, and is 
 * available at http://creativecommons.org/licenses/MIT/
 *
 * Contributors:
 *   Stephan D. Cote 
 *      - Initial concept and initial implementation
 */
package coyote.testdata;

/**
 * 
 */
public interface GenerationStrategy {

  /**
   * Generate data according to this strategy.
   * 
   * <p>The row for which data is to be generated to give the strategy the 
   * context for the data. This allows the strategy to generate data which 
   * makes sense for the rest of the elements. For example, a email generation 
   * strategy may try to find username or first/last names to generate a 
   * believable email address. A first name strategy may try to ascertain 
   * gender to generate an appropriate first name.</p>
   * 
   * @param row The row for which data is being generated.
   *  
   * @return The data generated by this strategy.
   */
  public Object getData( Row row );

}
